version: "3.8"
services:
  api:
    container_name: foodswift_api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: foodswift_api:1.0.0
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
