version: "3.8"
services:
  api:
    container_name: api_container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./app/node_modules
